name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:                             # Fixed job name typo from "debloy" to "deploy"
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: bizaXL/Frape-Docker
          ref: Devtest2
          token: ${{ secrets.PAT }}

      - name: Deploy app
        working-directory: ./action-workflow/action-workflow
        run: |
          docker-compose -f pwd.yml up -d

      
