name: docker-compose

on:
  workflow_dispatch:

jobs:
  deploy-frappe:
    runs-on: self-hosted
    name: Deploy Frappe with Docker Compose

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: bizaXL/Frape-Docker
          ref: Devtest1
          token: ${{ secrets.PAT }}

      - name: Update package list
        run: sudo apt update

      - name: Change to project directory
        run: cd ${{ github.workspace }}

      -name: useradd
        run: sudo usermod -aG docker $USER

      - name: Bring up services
        run: docker-compose -f pwd.yml up -d

      - name: List running containers
        run: docker ps
        
