name: docker-compose
on:
  workflow_dispatch:
jobs:
  deploy-frappe:
    runs-on: self-hosted
    name: Deploy Frappe with Docker Compose
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: bizaXL/Frape-Docker
          ref: Devtest1
          token: ${{ secrets.PAT }}
      - name: change directory
        run: cd /home/ubuntu/actions-runner/_work/action-workflow/action-workflow
      - name: Start Frappe with Docker Compose
        run: docker-compose -f pwd.yml up -d


        
