name: docker-compose
on:
  workflow_dispatch:
jobs:
  deploy-frappe:
    runs-on: self-hosted
    name: Deploy Frappe with Docker Compose
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: bizaXL/Frape-Docker
          ref: Devtest2
          token: ${{ secrets.PAT }}
      
      - name: Docker build
        run: |
          docker build \
            --no-cache \
            --tag=benedictdockeracc/build-image:v4 \
            --file=./Dockerfile .
        working-directory: /home/ubuntu/actions-runner/_work/action-workflow/action-workflow
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_password }}
      - name: Docker push
        run: docker push benedictdockeracc/build-image:v4

     


        
