name: image update

on:
  workflow_run:
    workflows:
      - "docker-compose.yml"    # workflow to wait for
    types:
      - completed                  # trigger when it completes

jobs:
  run-after-success:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}   # run only if previous workflow succeeded
    runs-on: self-hosted
    steps:
      - run: echo "Previous workflow succeeded, running this workflow now."
    -name: checkout
     uses: 
