name: Stable build

on:
  workflow_dispatch:

jobs:
  install-apache:
    runs-on: self-hosted
    name: install apache
    steps:
      - name: Update package list
        run: sudo apt update
        
      - name: Install Apache
        run: sudo apt install apache2 -y
        
      - name: Check Apache version
        run: sudo systemctl status apache2

        
      - name: Start Apache service
        run: sudo systemctl start apache2
        
      - name: Enable Apache service
        run: sudo systemctl enable apache2

